---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-application
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: dexne/go-web-application
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000